# Generated by Django 4.0.4 on 2022-05-12 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='active_level',
            field=models.CharField(choices=[('0', 'идет разработка курса'), ('1', 'идет набор на курс'), ('2', 'курс начался'), ('3', 'курс закончился')], default='0', max_length=1, verbose_name='статус курса'),
        ),
        migrations.AddField(
            model_name='settings',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='is_active',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='recruitment_start_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='start_date',
            field=models.DateTimeField(null=True),
        ),
    ]
