# Generated by Django 4.0.4 on 2022-05-12 11:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0004_settings_active_level_settings_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='recruitment_start_date',
        ),
        migrations.CreateModel(
            name='CoursEnrollment',
            fields=[
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='course.course')),
                ('tieme_create', models.DateTimeField(auto_now_add=True)),
                ('tieme_end', models.DateTimeField(null=True)),
                ('students', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': ('Набор на курс',),
                'verbose_name_plural': 'Набор на курс',
                'db_table': ' course_enrollment',
            },
        ),
    ]
