# Generated by Django 4.0.4 on 2022-05-12 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_remove_settings_recruitment_start_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursenrollment',
            old_name='tieme_create',
            new_name='time_create',
        ),
        migrations.RenameField(
            model_name='coursenrollment',
            old_name='tieme_end',
            new_name='time_end',
        ),
    ]
