# Generated by Django 4.0.4 on 2022-05-14 01:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0010_comment_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatingScore',
            fields=[
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='course.course')),
                ('mark', models.IntegerField(null=True)),
                ('student', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': ('Рейтинговая оценка',),
                'verbose_name_plural': 'Рейтинговые оценки',
                'db_table': 'rating_score',
            },
        ),
    ]
