# Generated by Django 4.0.3 on 2022-04-30 17:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0006_alter_lesson_is_published'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0039_course_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='РassingРrogress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_pass', models.BooleanField(default=False, null=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module.lesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': ('Прогресс прохождения',),
                'verbose_name_plural': 'Прогресс прохождения',
                'db_table': 'passing_progress',
            },
        ),
    ]
