# Generated by Django 4.0.3 on 2022-05-12 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0004_alter_file_block_alter_text_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
