# Generated by Django 4.0.3 on 2022-05-08 19:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0041_notifications'),
        ('module', '0006_alter_lesson_is_published'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('time_create', models.DateTimeField(auto_now=True)),
                ('time_deadline', models.DateTimeField(null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='files/%Y-%m-%d/')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module.module')),
            ],
            options={
                'verbose_name': ('Задание',),
                'verbose_name_plural': 'Задания',
                'db_table': 'task',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='StudentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='files/%Y-%m-%d/')),
                ('time_create', models.DateTimeField(auto_now=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='module.task')),
            ],
            options={
                'verbose_name': ('Ответ на задание',),
                'verbose_name_plural': 'Ответы на задания',
                'db_table': 'student_answer',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_create', models.DateTimeField(auto_now=True)),
                ('mark', models.IntegerField(null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='module.task')),
            ],
            options={
                'verbose_name': ('Оценка',),
                'verbose_name_plural': 'Оценки',
                'db_table': 'mark',
                'ordering': ('id',),
            },
        ),
    ]
