# Generated by Django 4.0.4 on 2022-05-12 01:51

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0006_alter_text_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
    ]
