# Generated by Django 4.0.3 on 2022-05-08 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0008_remove_mark_task_mark_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='answer',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='module.studentanswer'),
        ),
    ]
