# Generated by Django 4.0.4 on 2022-05-12 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0010_urllink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
