# Generated by Django 4.0.4 on 2022-06-20 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0012_block_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='block',
            name='level',
        ),
    ]
